theme: jekyll-theme-minimal
title: [Fight]
description: [Practise fight here]
logo: [AdityaBando/sight/logo-en-rojo-para-taekwondo.svg]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
